spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: postgres
    password: 12345
  #    username: admin
#    password:
#    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: PostgreSQLDialect
  security:
    user:
      name: user
      password: 12345


