spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    username: admin
    password:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
  security:
    user:
      name: user
      password: 12345

